name: Run tests

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]
  workflow_dispatch:  # Manually trigger the shared workflow

permissions:
  contents: read

jobs:
  build:
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16] # 14,
    steps:
      - uses: actions/checkout@v3
      
      - name: Start Fastci Tracer
        uses: fastci-dev/tracer-bin@main
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install Dependencies
        run: npm install
      
      # - name: Run tests
      #   run: |
      #     npm run test
      
      - name: Capture End Time
        id: end-time
        run: |
          end_time=$(ps -o etimes= -p $(pgrep -f "tracer") | tr -d '[:space:]')
          echo "Tracer process ended at $end_time seconds"
          
      - name: Publish to coveralls.io
        if: ${{ matrix.node-version == 14 }}
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
