name: Run tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure Git credentials
      run: |
        git config --global user.name "Yahav Ohana"
        git config --global user.email "yahav7070@gmail.com"

    - name: Authenticate with GitHub Package Registry
      run: echo "${{ secrets.PAT }}" | gh auth login --with-token

    - name: Run Unique Tracer Workflow
      uses: fastci-dev/tracer/.github/workflows/shared-workflow.yaml@main
      
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Run tests
      run: |
        npm run test
    - name: Publish to coveralls.io
      if: ${{ matrix.node-version == 14 }}
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ github.token }}
